### PR TITLE
Making custome sort parsers error resistent

### PR DESCRIPTION
**Pull request by anutron**
Issue is when you basically tell the sorter to use string or number but the DOM doesn't actually have a value. It's an error state, i.e. you shouldn't build your DOM that way to use this properly, but I didn't want it to just flat-out fail. When it does, it hides all the rows in the table (because it breaks during the sort when they are popped out of the DOM).

### CODE REVIEW

**Comment by drn** [comment]
check typos in commit message
custome -> custom
resistent -> resistant

**Comment by drn** [comment]
lgtm otherwise

**Comment by anutron** [comment]
lulz. thanx.

**Comment by davywentworth** [comment]
this commit message looks like Ye Olde English.

**Pull request closed without merging**
